/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("AssetsObjectPageObjectPage journey");

        opaTest("Navigate to AssetsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheAssetsList.onFilterBar().iExecuteSearch();

            Then.onTheAssetsList.onTable().iCheckRows();
            When.onTheAssetsList.onTable().iPressRow(0);

            Then.onTheAssetsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheAssetsObjectPage.iCheckSection({ section: "FieldGroup::Details" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "serialNumber" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "model" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "hardwareType/name" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "status" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "vendor" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "currentEmployee/name" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "price" });
            Then.onTheAssetsObjectPage.onForm({ section: "FieldGroup::Details" }).iCheckField({ property: "purchaseDate" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});